Fix image pixelated when DPR is not an integer
deepin-community/fcitx5-configtool pull request #5
Opened 2024-02-26 03:22 UTC by kegechen

use devicePixelRatioF() instead of devicePixelRatio()

Issue: https://github.com/linuxdeepin/developer-center/issues/7166

2024-02-26 03:35 UTC, xzl01 requested changes
上游项目进行更改需要以patch的形式进行

2024-02-26 03:38 UTC, kegechen commented
上游提交    https://github.com/fcitx/fcitx5-configtool/pull/73

2024-02-26 03:45 UTC, kegechen commented
/integrate

2024-02-26 05:03 UTC, xzl01 approved these changes

2024-02-26 05:29 UTC, UTsweetyfish commented
/hold

2024-02-26 05:29 UTC, UTsweetyfish commented
> 上游提交 [fcitx/fcitx5-configtool#73](https://github.com/fcitx/fcitx5-configtool/pull/73)

有上游提交也需要以 quilt patch 提

2024-02-26 05:30 UTC, UTsweetyfish commented
而且没改 d/changelog

2024-02-29 01:37 UTC, kegechen commented
/merge

2024-02-29 01:38 UTC, kegechen commented
@xzl01 测试通过了

2024-02-29 06:37 UTC, merged